#
# Control the state of the battery charger, two FETs, and
# the drive motors.
# Each attribute can have one of three possible values:
#
#  'ON' - enable, even if already enabled
#  'OFF' - disable, even if already disabled
#  'IGNORE' - don't change the state
#

string set_charger
string set_fet1
string set_fet2
string set_motors
---
bool success
